import type { Metadata } from "next";
import "./globals.scss";
import SessionWrapper from '../../components/SessionWrapper';
import styles from './page.module.scss'
import NavigationBar from '../../components/NavigationBar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <SessionWrapper>
          <div className={styles.page}>
            <NavigationBar />
            {children}
          </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
